Play travis
otus-devops-2019-05/ArtemAdm_infra pull request #3
Opened 2019-06-17 19:56 UTC by ArtemAdm

2019-06-17 20:20 UTC, mrgreyves requested changes
Здравствуйте!) Вам нужно починить тесты тревиса, так же нужно добавить описание к пр.

2019-06-18 16:40 UTC, ArtemAdm commented
Выполнено :)

2019-06-18 20:03 UTC, mrgreyves commented
Описание пуллреквеста забыли добавить =(

2019-06-18 20:03 UTC, mrgreyves requested changes
Про описание забыли =(

2019-06-19 05:20 UTC, ArtemAdm commented
В лабе было написано.
В PR добавлять в Reviewers никого не нужно
Я заполнил файл PULL_REQUEST_TEMPLATE.md

2019-06-19 05:24 UTC, ArtemAdm commented
# Выполнено ДЗ №2

 - [v] Основное ДЗ

## В процессе сделано:
 - Пункт 1 //Закрепление знаний по Git
 - Пункт 2 //Создание интеграции с чатом с репозиторием и подключение TravisCI

## Закрепление знаний по Git
 - повторение стандартных команд на индесирование, коммитировние, изминение предыдущих коммитов, удаление коммитов
 - повторение работы с ветками их добавление, переход по веткам
 - работа с удалённым репозиторием GitHub, слияние веток 

## Интеграция Slack с Travis CI
 - Пункты указанные в методичке были успешно выполнены
 - Нужно было найти ошибку в скрипте test.py . В тесте self.assertEqual(1 + 1, 1) была ошибка в уровнении 1 + 1 не равняеться 1. Исправлено уровнение на (1 + 1, 2) и тревис загорелся зеленым.

## P.S. было тяжело :)

Вот такой комментарий к PR должен быть ? 
Или нужно описать свои комментарии? На выходных только смогу пересмотреть 3ю лекцию.

2019-06-19 10:57 UTC, mrgreyves commented
Здравствуйте!) Да, комментарий должен быть примерно такой=)

2019-06-19 10:58 UTC, mrgreyves commented
Я перенес ваш комментарий в описание пр. В дальнейшем там и оформляйте. И переоткройте пр =)

2019-06-19 13:19 UTC, mrgreyves approved these changes
Апрув!)

2019-06-19 17:44 UTC, merged